### PR TITLE
Added darkmode.css (WIP) and fixed chat and chat images.

### PR DESCRIPTION
**Pull request by zeyus**
Darkmode is a bit ugly in the instagram feed but looks fine in chat

image

image

image

### CODE REVIEW

**Comment by reikolydia** [comment]
image

here is what it looks like on the login screen, i think we can work on this

**Comment by zeyus** [comment]
Haha yeah that looks awful with darkmode, feel free to push a fix to this
branch if you want to mess around with it

**Review by reikolydia — APPROVED** [review]
The target audience is amoled black, or just eye saving dark? still, a good start in the right direction

**Comment by zeyus** [comment]
> 
> 
> The target audience is amoled black, or just eye saving dark? still, a good start in the right direction

I have an IPS IGZO display on my laptop and there are some savings with complete black, but mainly it's just personal preference (i was loosely basing it on the messenger recipe theme) but I don't really mind either way

**Pull request merged**
